#!/usr/bin/env bash

# zsh plugins settings

# zsh-syntax-highlighting 
typeset -A ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[path]=none
ZSH_HIGHLIGHT_STYLES[path_prefix]=none
ZSH_HIGHLIGHT_STYLES[precommand]='fg=green,underline=none'
ZSH_HIGHLIGHT_STYLES[autodirectory]='underline=none'
