#!/usr/bin/env bash

export TERM=xterm-256color

# Make vim the default editor.
export EDITOR=nvim

# Increase Zsh history size.
export HISTSIZE=50000

# Prefer US English and use UTF-8.
export LANG=en_US.UTF-8
